#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3

void keyboard_post_init_user(void) {
	pimoroni_trackball_set_rgbw(0,254,254,0);
}

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(KC_EXLM, KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT, KC_MINS, KC_TAB, KC_A, LALT_T(KC_R), LGUI_T(KC_S), LCTL_T(KC_T), KC_G, KC_M, RCTL_T(KC_N), RGUI_T(KC_E), RALT_T(KC_I), KC_O, KC_QUOT, KC_NO, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_QUES, KC_NO, LSFT(KC_LSFT), LT(1,KC_ESC), KC_SPC, LT(2,KC_ENT), KC_BSPC),

[_LAYER1] = LAYOUT(KC_NO, KC_AT, KC_LCBR, KC_RCBR, KC_COLN, KC_NO, KC_NO, KC_AMPR, KC_SLSH, KC_BSLS, KC_PERC, KC_NO, KC_NO, KC_HASH, LALT_T(KC_LPRN), LGUI_T(KC_RPRN), LCTL_T(KC_SCLN), KC_GRV, KC_PIPE, RCTL_T(KC_ASTR), RGUI_T(KC_UNDS), LALT_T(KC_EQL), KC_EXLM, KC_NO, KC_NO, KC_LT, KC_LBRC, KC_RBRC, KC_GT, KC_NO, KC_NO, KC_PLUS, KC_MINS, KC_TILD, KC_CIRC, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, TG(3), KC_TRNS),

[_LAYER2] = LAYOUT(KC_F1, KC_F4, KC_6, KC_5, KC_4, KC_BTN2, KC_INS, KC_DEL, KC_PSCR, KC_SCRL, KC_F7, KC_F10, KC_F2, KC_F5, LCTL_T(KC_3), LGUI_T(KC_2), LALT_T(KC_1), KC_BTN1, KC_LEFT, RALT_T(KC_DOWN), RGUI_T(KC_UP), RCTL_T(KC_RGHT), KC_F8, KC_F11, KC_F3, KC_F6, KC_9, KC_8, KC_7, KC_BTN3, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_F9, KC_F12, KC_TRNS, LT(3,KC_0), KC_TRNS, KC_TRNS, KC_TRNS),

[_LAYER3] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_MOD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_RMOD, RGB_TOG, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS) 


};
